INSERT IGNORE INTO ciudades (id, nombre) VALUES (1, "Armenia"), 
                                                (2, "Barranquilla"),
                                                (3, "Bello"),
                                                (4, "Bogotá"),
                                                (5, "Bucaramanga"),
                                                (6, "Cali"),
                                                (7, "Cartagena"),
                                                (8, "Cúcuta"),
                                                (9, "Ibagué"),
                                                (10, "Manizales"),
                                                (11, "Medellín"),
                                                (12, "Montería"),
                                                (13, "Neiva"),
                                                (14, "Pasto"),
                                                (15, "Pereira"),
                                                (16, "Santa Marta"),
                                                (17, "Soacha"),
                                                (18, "Soledad"),
                                                (19, "Valledupar"),
                                                (20, "Villavicencio");